#####################################
###                               ###
###  BlazeFly Configuration file  ###
###                               ###
#####################################


##      Main settings       ##
##############################
    # Check and alert when a newer version is available
    updateChecker: true
    # Message admins as they log in if a new version is available
    notifyAdmin: true
    # The name of the block to be used as fuel
    fuelBlock: "BLAZE_ROD"
    # If you don't know what this is, leave it as 0
    fuelSubdata: 0
    # The time in seconds each block of fuel will last
    fuelTime: 60
    # The name of the block to be used as fuel for VIPs
    VIPBlock: "COAL"
    # If you don't know what this is, leave it as 0
    VIPSubdata: 0
    # The time in seconds each block of fuel will last for VIPs
    VIPTime: 120
    # Amount of fuel to use while grounded (0.5 = half, 1 = full, etc)
    groundFuel: 0.25
    # Enables the use of /flyspeed to modify the flight speed
    allowSpeed: true
    # Flying fast will cost more fuel (eg. 2x speed halves fuelTime)
    speedFuel: true
    # Flight will be disabled for a user if they take any damage
    breakableWings: true
    # The time in seconds until wings heal
    healTime: 15
    # Protect players from fall damage due to fuel running out
    fallProtection: true

    # A list of worlds that BlazeFly will be disabled in
    disabledWorlds:
        - 'world_nether'
        - 'world_end'


##     String settings      ##
##############################
    header: "&6[BlazeFly] &7"
    permission: "&CYou do not have permission to use this command"
    reload: "Configuration reloaded"
    disabled: "Flight is currently disabled in this world"
    
    flyoffAdmin: "Flight has been disabled for %player%"
    flyoffPlayer: "Flight has been disabled for you by an administrator"
    notOnline: "%player% is not online"
    notFlying: "%player% is not currently flying"
    
    wBroke: "Your wings have been damaged, you're unable to fly"
    wBroken: "You cannot fly with damaged wings"
    wHealed: "Your wings have recovered"

    fEnabled: "Flight enabled"
    fDisabled: "Flight disabled"
    fReload: "Flight has been disabled due to a server reload"
    fRequired: "Flight requires fuel"
    fLast: "WARNING: You are now on your last block of fuel!"
    fOut: "You are out of fuel, flight has been disabled"

    fsDisabled: "Flyspeed is currently disabled"
    fsFlight: "Flight must be enabled to use flyspeed"
    fs1: "Flyspeed set to x1"
    fs2: "Flyspeed set to x2"
    fs4: "Flyspeed set to x4"
    fsOptions: "The options for flyspeed are 1, 2, 4"
    
    fuelStart: "Start flying to use this command"
    fuelNA: "You don't require fuel to fly"
    fuelMessage: "You have %seconds% seconds of fuel remaining at flyspeed %flyspeed%"